name: quote_of_the_day_mobile
description: "Personalized Quote of the Day mobile application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.8"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^9.2.4
  flutter_stripe: ^12.0.2
  flutter_svg: ^2.2.1
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  http: ^1.2.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  retrofit: ^4.7.2
  riverpod_annotation: ^3.0.0
  sentry_flutter: ^9.6.0
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mockito: ^5.5.0
  patrol: ^3.19.0
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/custom_icons.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated